# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubUsers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubUsers
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxGesture'
  pod 'RxSwiftExt'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'R.swift'
  pod 'SnapKit'

  target 'GitHubUsersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubUsersUITests' do
    # Pods for testing
  end

end
